### ISSUE TITLE
source ~ IGN shouldn't be an issue anymore

### ISSUE THREAD

**Issue by thibdrev** [osm-fr/osmose-backend#114]
Now that IGN allows OSM to use the BD Ortho, the analysis should accept when "IGN" is given as a source (or at least accept IGN+ortho)

**Comment by jocelynj** [comment]
Thanks for the report. It is now fixed on master.

**Comment by ray66** [comment]
It seem that this issue is back again. Objects with source="IGN BD Topo Hydrographie 2017" are reported with code 3020 "Illegal or incomplete source tag IGN" although this source is LO/OL since may 2017.

**Comment by frodrigo** [comment]
#730 730
