### ISSUE TITLE
Stop suggesting (wrong) operator:wikidata for postboxes in Switzerland

### ISSUE THREAD

**Issue by dafadllyn** [osm-fr/osmose-backend#1302]
Osmose suggests adding the following tags to some postboxes in Switzerland:

```
operator:de = Die Post
operator:en = Swiss Post
operator:fr = La Poste
operator:it = La Posta
operator:wikidata = Q614803
operator:wikipedia = de:Die Schweizerische Post 
```

First of all, the `operator:wikidata` tag is wrong. The correct Wikidata entry for "Post CH AG" (brand names: "Die Post" (German), "La Poste", (French), "La Posta" (Italian and Romansh), "Swiss Post" (English)), the company responsible for the postal services in Switzerland, is [Q107231758](https://www.wikidata.org/wiki/Q107231758), not [Q614803](https://www.wikidata.org/wiki/Q614803). Q614803 is the Wikidata entry for "Die Schweizerische Post AG", the parent organisation of "Post CH AG", to which "PostFinance AG" (financial institution) and "PostAuto AG" (bus company) also belong.

Second, the collection times of about 90% of post boxes throughout Switzerland has changed on May 31 this year (see [1] and [2]). If you persuade people to add these partially wrong and little important tags to postboxes ("Post CH AG" is the only operator of postboxes in Switzerland), this creates new object versions, suggesting that the postboxes have been inspected on site recently and not appearing anymore on Overpass queries that have been created to find the possibly outdated postboxes. [3]

Therefore i ask you to stop suggesting the aforementioned tags to postboxes in Switzerland.

[1]: https://lists.openstreetmap.ch/pipermail/talk-ch/2021-June/010929.html
[2]: https://lists.openstreetmap.ch/pipermail/talk-ch/2021-June/010962.html
[3]: https://overpass-turbo.eu/s/18m2

**Comment by frodrigo** [comment]
This suggestion come from the NSI project.
The data should be fixed on this project

https://nsi.guide/index.html?t=operators&k=amenity&v=post_office&tt=post&cc=ch
https://github.com/osmlab/name-suggestion-index

**Comment by dafadllyn** [comment]
Okay, i've found the mistake in name-suggestion-index and [proposed a fix](https://github.com/osmlab/name-suggestion-index/pull/5145).

However, this does not solve the second problem mentioned above, i.e. postboxes getting new versions, thus giving false impressions that they have been inspected and that their collection times were up do date.

**Comment by frodrigo** [comment]
> Okay, i've found the mistake in name-suggestion-index and [proposed a fix](https://github.com/osmlab/name-suggestion-index/pull/5145).
> 
> However, this does not solve the second problem mentioned above, i.e. postboxes getting new versions, thus giving false impressions that they have been inspected and that their collection times were up do date.

In OSM you cannot assume last date version of object is the last survey date. There is a tag for that https://wiki.openstreetmap.org/wiki/Key:survey:date

**Comment by dafadllyn** [comment]
> In OSM you cannot assume last date version of object is the last survey date. There is a tag for that https://wiki.openstreetmap.org/wiki/Key:survey:date

Of course not always, but why would you change a postbox if you didn't inspect it on site? In my opinion, adding `operator:<language>=*` and `operator:wikidata=*` tags to postboxes is of little use, especially because, as mentioned, Swiss Post (Post CH AG) is the only operator of postboxes in Switzerland.

**Comment by dafadllyn** [comment]
PS: Unfortunately, very few people set `survey:date=*`.
