### ISSUE TITLE
Rerun "Redirected value for Wikidata tag"

### ISSUE THREAD

**Issue by matkoniecz** [osm-fr/osmose-backend#2114]
https://osmose.openstreetmap.fr/en/issue/df2d571b-4e40-501d-9745-26df291e7943

```
source 	427971
item 	3031
class 	3
lat lon 	50.0630528 19.9366344
title 	
en 	Redirected value for Wikidata tag
subtitle 	
en 	Wikidata item is redirected to Q30171502.
timestamp 	2023-11-05 19:45:12+00:00
detail 	
en 	This Wikidata item is a redirect, you shoud change the QID to the redirect destionation.
fix 	
en 	Change the value of the affected tag to the suggested new Wikidata-ID.
source code 	https://gitlab.com/geometalab/osm-wikidata-quality-checker 
```

this and similar persists despite https://www.openstreetmap.org/changeset/143409952 fixing them two months ago

**Comment by matkoniecz** [comment]
Also, in general reporting it at all is utterly pointless. It is something that should never be fixed by humans, wasting human time on this is a terrible waste of time.

This is something that should be done by bot or not at all.

(if you think that in some area bot edit would be welcome - or maybe that global one would be accepted - feel free to propose one in accordance with https://wiki.openstreetmap.org/wiki/Automated_Edits_code_of_conduct#Document_and_discuss_your_plans  running bot described https://wiki.openstreetmap.org/wiki/Mechanical_Edits/Mateusz_Konieczny_-_bot_account/fixing_wikidata_tags_pointing_at_redirects_in_Poland / https://wiki.openstreetmap.org/wiki/Mechanical_Edits/Mateusz_Konieczny_-_bot_account/fixing_wikidata_tags_pointing_at_redirects_in_USA - if bot edit would be accepted I will run it)

**Comment by frodrigo** [comment]
This analyses is run by Swiss students, and for now it does not have been updated for two months.

> Also, in general reporting it at all is utterly pointless. It is something that should never be fixed by humans, wasting human time on this is a terrible waste of time.
> This is something that should be done by bot or not at all.

I am agree with you. But here on Osmose-QA side, we report data issues, we does not fix the data. When issues are simple and occur too often a bot is also for me a good choose. QA reporting help to see when and where it could be required.

I am not planning running a bot myself nor thinking it is in the Osmose-QA scope.

**Comment by matkoniecz** [comment]
> This analyses is run by Swiss students, and for now it does not have been updated for two months.

Is there a way to ping them? Maybe it should removed from being displayed?

**Comment by frodrigo** [comment]
> > This analyses is run by Swiss students, and for now it does not have been updated for two months.
> 
> Is there a way to ping them? Maybe it should removed from being displayed?

It s automatic, after 3 months.
