### ISSUE TITLE
"no translation" in frontend menu

### ISSUE THREAD

**Issue by fgouget** [osm-fr/osmose-backend#228]
https://osmose.openstreetmap.fr/en/map/

If I go to this URL, right below "gas station, could be integrated" in the menu I get an entry called "no translation".

In fact this should be "Gas station update" (see analysers/analyser_merge_fuel_FR.py:30).
However I did not find why this one gets displayed wrong and not the items on the previous lines.

Note that the "no translation" text comes from osmose-frontend/tools/query_meta.py.

**Comment by frodrigo** [comment]
Done in osmose-front-end source code.

**Comment by fgouget** [comment]
Has this specific update been put online? I see that there have been some changes in Osmose but I'm still seeing "no translation":

![image](https://user-images.githubusercontent.com/1897397/31696332-bfc92630-b3b0-11e7-898e-082cb990b726.png)
