### ISSUE TITLE
Keep the protocol when redirecting an api route

### ISSUE THREAD

**Issue by GuillaumeAmat** [osm-fr/osmose-backend#247]
If I call the route:
https://osmose.openstreetmap.fr/api/0.2/errors?item=8120

I'm redirected to the route:
http://osmose.openstreetmap.fr/fr/api/0.2/errors?item=8120

The **https** protocol is now **http**. It should remain **https**.

**Comment by jocelynj** [comment]
I don't have this behaviour here. I've tried with both firefox and chrome, and I stay in https.

Can you give more information, like the browser, or the network debug trace ?

**Comment by jocelynj** [comment]
Ah, you're right: using `wget -4 https://osmose.openstreetmap.fr/api/0.2/errors?item=8120` gives me a redirection. With -6, I don't have any redirection.

**Comment by jocelynj** [comment]
It should be fixed, by modifying the settings on nginx proxy to redirect in https instead of http.

@frodrigo I'm a bit surprised by the fact the /api URL is doing a redirection to /en/api. Is it expected ?

**Comment by GuillaumeAmat** [comment]
Thank you but I'm still experiencing that issue...
[Archive 17-11-19 13-09-13.zip](https://github.com/osm-fr/osmose-backend/files/1485518/Archive.17-11-19.13-09-13.zip)

**Comment by frodrigo** [comment]
Yes. The app is mounted on all languages, there is no default app.

**Comment by jocelynj** [comment]
@GuillaumeAmat That's very strange ...

Can you provide a log from this command line:
```
wget -4 "https://osmose.openstreetmap.fr/api/0.2/errors?item=8120"
```

Here, I have the following results:
```
$ wget -4 "https://osmose.openstreetmap.fr/api/0.2/errors?item=8120"
--2017-11-19 19:07:37--  https://osmose.openstreetmap.fr/api/0.2/errors?item=8120
Résolution de osmose.openstreetmap.fr (osmose.openstreetmap.fr)… 88.191.250.200
Connexion à osmose.openstreetmap.fr (osmose.openstreetmap.fr)|88.191.250.200|:443… connecté.
requête HTTP transmise, en attente de la réponse… 302 Found
Emplacement : https://osmose.openstreetmap.fr/en/api/0.2/errors?item=8120 [suivant]
--2017-11-19 19:07:37--  https://osmose.openstreetmap.fr/en/api/0.2/errors?item=8120
Réutilisation de la connexion existante à osmose.openstreetmap.fr:443.
requête HTTP transmise, en attente de la réponse… 200 OK
Taille : 5363 (5,2K) [application/json]
Sauvegarde en : « errors?item=8120 »

errors?item=8120                      100%[=========================================================================>]   5,24K  --.-KB/s    in 0,001s  

2017-11-19 19:07:37 (3,48 MB/s) — « errors?item=8120 » sauvegardé [5363/5363]
```

**Comment by GuillaumeAmat** [comment]
Weird... I've got the same output:

```
$ wget -4 "https://osmose.openstreetmap.fr/api/0.2/errors?item=8120"
--2017-11-19 19:15:55--  https://osmose.openstreetmap.fr/api/0.2/errors?item=8120
Résolution de osmose.openstreetmap.fr (osmose.openstreetmap.fr)… 88.191.250.200
Connexion à osmose.openstreetmap.fr (osmose.openstreetmap.fr)|88.191.250.200|:443… connecté.
requête HTTP transmise, en attente de la réponse… 302 Found
Emplacement : https://osmose.openstreetmap.fr/en/api/0.2/errors?item=8120 [suivant]
--2017-11-19 19:15:55--  https://osmose.openstreetmap.fr/en/api/0.2/errors?item=8120
Réutilisation de la connexion existante à osmose.openstreetmap.fr:443.
requête HTTP transmise, en attente de la réponse… 200 OK
Taille : 5363 (5,2K) [application/json]
Sauvegarde en : « errors?item=8120 »

errors?item=8120                                                100%[======================================================================================================================================================>]   5,24K  --.-KB/s    ds 0s      

2017-11-19 19:15:55 (73,3 MB/s) — « errors?item=8120 » sauvegardé [5363/5363]
```

But when I do it in my browser or even from Node.js, I got the issue.

**Comment by frodrigo** [comment]
There is issues with JOSM remote and https. Whe ave to keep it as http.

@GuillaumeAmat You have to use an URL with language to avoir redirect.

@jocelynj Maybe we can split the app to not have to mount the API with language path.

**Comment by GuillaumeAmat** [comment]
@frodrigo Why don't you just keep the request protocol?

If I do a request with http, I stay with http.
If I do a request with https, I stay with https.

**Comment by frodrigo** [comment]
Sorry, I reread all, and I see I misunderstood the issue.

But if you set langue in the URL, you will not get redirect. So my answer is still correct ;-).

**Comment by frodrigo** [comment]
@jocelynj I have no idea where the redirect come from. For sure it's from the python part.

**Comment by jocelynj** [comment]
@GuillaumeAmat I still don't understand where it can come from.

Can you retry from your browser, after having flushing your cache ?  (and with control-F5 to force a refresh)  If it is still not working, please provide the exact time of the request, so that I can look at server logs.

**Comment by GuillaumeAmat** [comment]
@frodrigo Still correct yes ;)
But for the need of [osmose-request](https://github.com/GuillaumeAmat/osmose-request) I wanted to use a language agnostic endpoint such as: https://osmose.openstreetmap.fr/api/0.2

@jocelynj It's working now, thank you! :)

**Comment by frodrigo** [comment]
@GuillaumeAmat But the content returned by the API is translated

**Comment by GuillaumeAmat** [comment]
Indeed... But the choice of the language has to be done by the user, not by my default endpoint configuration.

Can you tell me how Osmose detects the language of the API user? I will set the right HTTP header in the osmose-request requests in order to be redirected to the right route and have the good translations.

**Comment by frodrigo** [comment]
There is no detection on Osmose side. It's only depends on the URL.

**Comment by frodrigo** [comment]
@jocelynj I got the redirect: https://github.com/osm-fr/osmose-frontend/blob/master/bottle_gettext.py#L83

@GuillaumeAmat And good new, it come with a language detection based on Accept-Language

Sorry, I forgot a bit about code I write 5y ago

**Comment by GuillaumeAmat** [comment]
No problem ;) I will test that.

**Comment by GuillaumeAmat** [comment]
It works like a charm, thank you!
