### ISSUE TITLE
1221 "Object must be close to coast or water" on leisure=slipway nodes in contact with water.

### ISSUE THREAD

**Issue by osm-spiregrain** [osm-fr/osmose-backend#325]
I've got three issues with slipways showing - these three:
- https://osmose.openstreetmap.fr/en/error/19563160611
- https://osmose.openstreetmap.fr/en/error/19563160610
- https://osmose.openstreetmap.fr/en/error/19563160609

All of them are "Object must be close to coast or water" relating to a slipway node that is connected to the edge of a navigable river and a service road.   That is in accordance with the wiki definition of https://wiki.openstreetmap.org/wiki/Tag:leisure=slipway . 

I *think* Osmose is misreporting these three.  At least, they are all close to water, so maybe there is another problem and the wording is misleading.

**Comment by frodrigo** [comment]
This part of Thames have a lot of this kind of issues raised.
Maybe there a is or was problem with this way https://www.openstreetmap.org/way/515061721

**Comment by osm-spiregrain** [comment]
That section of the Thames (and some others) have an undocumented tag "bezier=no"; otherwise nothing *looks* wrong.

**Comment by frodrigo** [comment]
I found a bug in Osmose for the way 515061721. The geometry is lost on this analysis. Still on it.

**Comment by frodrigo** [comment]
The way is across the boundary extract and some nodes referred by the way are not in the extract.
It is http://download.geofabrik.de/europe/great-britain/england/greater-london.html
@jocelynj do you know if it's the general behaviours of Geofabirk extraction ?

**Comment by jocelynj** [comment]
According to https://download.geofabrik.de/technical.html:
> The Osmium extract function that we use keeps ways and multipolygon relations that cross an extract border complete, i.e. when a very large mutlipolygon crosses the border, an extract can occasionally contain a lot more that expected. 

So we should have the full way on this extract if part of this way is inside it. I'm downloading it to check - can you provide an id for a node you see missing ?

**Comment by jocelynj** [comment]
In fact, this extract is downloaded from http://download.openstreetmap.fr/extracts/europe/united_kingdom/england/greater_london-latest.osm.pbf, not from geofabrik.

**Comment by jocelynj** [comment]
I've re-generated the extract with the correct osmosis command to keep nodes and ways that are outside the polygons. This should fix this issue.

**Comment by frodrigo** [comment]
I rerun an import and  the analyser. Same problem, node still missing in data base.

**Comment by osm-spiregrain** [comment]
Those three have dropped off my Osmose list, and the three URLs above don't work anymore, so I guess it's all fixed.

Many thanks to everyone involved.
