### ISSUE TITLE
opening hours parser is incomplete and produces lots of false positives

### ISSUE THREAD

**Issue by simonpoole** [osm-fr/osmose-backend#433]
I would suggest disabling the check globally as it is far from correct and highlighting lots of issues with perfectly good OH strings.

Example: it complains about opening_hours = Mo-Sa 07:00-19:00; PH Su off 

Which is perfectly OK, see https://wiki.openstreetmap.org/wiki/Key:opening_hours/specification#explain:weekday_selector

Note: it is likely that the mapper in question actually should have used PH,Su but that is not the point. 

Other example: the relatively commonly used weekday in month syntax is completely missing from the BNF for the parser in OSMOSE.

See https://wiki.openstreetmap.org/wiki/Key:opening_hours/specification#explain:weekday_range:nth_entry

**Comment by frodrigo** [comment]
@rezemika are you able to fix your parser?

**Comment by rezemika** [comment]
Yes, it's done. Check the `0.1.8` version of oh_sanitizer. Sorry for the inconvenience.

**Comment by rezemika** [comment]
I'll check this as soon as possible, sorry for the delay (I am in exam period).

**Comment by frodrigo** [comment]
Thank you. For now I take the 0.1.9.

**Comment by frodrigo** [comment]
http://osmose.openstreetmap.fr/en/errors/graph.png?item=3250&class=32501&start_date=2019
Look good. It removes 10% of issues.

**Comment by dex2000** [comment]
Other example:

    We-Sa 18:00+

is marked as error.
Like: http://osmose.openstreetmap.fr/de/error/22862069211

**Comment by rezemika** [comment]
I am currently working on a project which will be able to parse and correct almost all fields. However, it will take a long to complete. So, in the mean time, it may indeed be relevant to disable the OH checking.
Sorry for the inconvenience.

**Comment by frodrigo** [comment]
@rezemika a completely different project? Should I remove OH checking from Osmose or just disable it?

**Comment by simonpoole** [comment]
@rezemika why? There are a number of fairly to very complete parsers including my javacc one (that in principle could generate c++ code too).

**Comment by rezemika** [comment]
Not really, it would be a next major version of `humanized_opening_hours` (but with a quite good retro-compatibility), which will be able to parse, sanitize and understand almost all valid fields. However, it's probably a matter of weeks before a stable release (my free time is so rare), so it may be relevant for you to find an alternative...

**Comment by frodrigo** [comment]
OK I disable it. For Osmose there is no need of retro-compatibility.

**Comment by frodrigo** [comment]
@simonpoole I don't know about the other OH parser. But the idea was to have a fault tolerant parser able to produce fix suggestion.

**Comment by frodrigo** [comment]
@fgouget provide a MR for improved oh_sanitizer #444

**Comment by frodrigo** [comment]
Contrib of @fgouget merged, and plugin re-enabled.

**Comment by deuzeffe** [comment]
Hello,

The "new" parser flags "opening_hours = 24/7" as invalid :-(

**Comment by fgouget** [comment]
The module was missing test for "24/7". However I added some and they pass!
But there are two rules hanging off of selector_sequence that have the same priority so maybe that's just luck. So I raised the 24/7 rule priority:

https://github.com/fgouget/osmose-backend/commit/de6fa15f99ce6a2851a4caa1d56d71b6b035f4ac

**Comment by frodrigo** [comment]
The 24/7 bug is now fixed (and others). Almost all areas are now up to date.
- http://osmose.openstreetmap.fr/fr/errors/graph.png?item=3250&class=32501&start_date=2019-02
- http://osmose.openstreetmap.fr/fr/errors/?item=3250&class=32501

Please still be attentive at the output of this check.

**Comment by fgouget** [comment]
Looks like there is still a problem with dates. For instance it tried to change "May 01 off" into "May 01:00 off" :-(
http://osmose.openstreetmap.fr/fr/error/23719907359

The rest looks good.

**Comment by frodrigo** [comment]
The area is Paris, and I confirm the analyser and the data are update.

One of my commit is about fixing the the "off".

I have doubt about the choose and usability of lark parser to do this job. Maybe linked to different version of lark parser and or version of python.

**Comment by frodrigo** [comment]
If nobody able to maintain or fix this plugin I will disable it. Sorry for all time already spend on it.
Too many issues opened on it #433 #490 #492 #498.

**Comment by frodrigo** [comment]
This item is now hidden on the Osmose Frontend.
Can be accessed via http://osmose.openstreetmap.fr/en/errors/?item=3250&useDevItem=all
