### ISSUE TITLE
Monument historique sans attribut “ref:mhs” ou incorrect

### ISSUE THREAD

**Issue by williamdes** [osm-fr/osmose-backend#591]
http://osmose.openstreetmap.fr/fr/error/30936735272

name | value
-- | --
source | 5150
item | 7080
class | 2
subclass | 0

http://osmose.openstreetmap.fr/fr/map/#zoom=18&lat=49.440024&lon=1.099078&item=7080&level=1%2C2%2C3&tags=&fixable=

I see many many false positives everywhere, can you re-process the issues and close them ?

Dupe of #517 ?

Same error for FINESS on #587

**Comment by frodrigo** [comment]
http://osmose.openstreetmap.fr/en/errors/graph.png?item=7080&start_date=2019

There is bug, all HM are marked.

**Comment by frodrigo** [comment]
Part of HM are dropped because the geocoding fail.

**Comment by frodrigo** [comment]
Done.

**Comment by williamdes** [comment]
@frodrigo The false-positives are still not cleared, is that expected ?

**Comment by frodrigo** [comment]
No. It should be OK.

**Comment by frodrigo** [comment]
It is rigth for me
http://osmose.openstreetmap.fr/en/errors/graph.png?item=7080&start_date=2019

Do you have a link?

**Comment by williamdes** [comment]
http://osmose.openstreetmap.fr/fr/error/31718615537

**Comment by williamdes** [comment]
http://osmose.openstreetmap.fr/fr/map/#zoom=7&lat=48.195&lon=0.955&item=7080&level=3&tags=&fixable=

**Comment by williamdes** [comment]
here is a screenshot
![image](https://user-images.githubusercontent.com/7784660/64082224-ed3c5800-cd0b-11e9-8cec-ae31e6955439.png)

**Comment by frodrigo** [comment]
Ok, your HM is on 3 municipalities, so it have 3 ref.

I merge all and move the tags on the building. Because the castle was mapped 4 times... But I guess it is not linked with this issue.

**Comment by williamdes** [comment]
I do not understand

and for this one ? http://osmose.openstreetmap.fr/fr/error/31718615868

**Comment by williamdes** [comment]
Do you mean that the message works also for duplicated refs ?

https://www.openstreetmap.org/changeset/73982372

**Comment by williamdes** [comment]
I randomly picked another one and checked with overpass turbo and did not find any duplicates

https://osmose.openstreetmap.fr/fr/error/31718615987
https://overpass-turbo.eu

**Comment by frodrigo** [comment]
There are no duplicate. There are multiple refs for the same HM.
`ref:mhs=PA29000043;PA29000044;PA29000045`

**Comment by williamdes** [comment]
Okay, can you implement a suggestion so it becomes clear that you need to add all refs
(online correction for Osmose)

Please :)

**Comment by frodrigo** [comment]
It is not a general case and not really append often.

I think it's not linked with your issue, to be confirmed.

**Comment by williamdes** [comment]
As you can see on the map there is a lot of errors, if there are not duplicates I would be very happy to know what is wrong to fix the errors :)

**Comment by williamdes** [comment]
For https://osmose.openstreetmap.fr/fr/error/31775196863
what is wrong ?

The error message is not enough explicit on what is really wrong.

"Historical monument without tag "ref:mhs" or invalid"

Historical monument without tag : NO
Historical monument ~~without tag "ref:mhs"~~ or invalid : NO (the ref is a valid one)

What is left ?

I did not find other codes in the database, can you implement a way to help us reduce the number of errors ?

**Comment by frodrigo** [comment]
The falback of geocoding fails to Opendata coordinates does not work.

https://github.com/osm-fr/osmose-backend/blob/master/analysers/analyser_merge_heritage_FR_merimee.py#L99
https://github.com/osm-fr/osmose-backend/blob/master/analysers/Analyser_Merge.py#L670-L671

**Comment by frodrigo** [comment]
Done, from 1000 issues to 300.
